// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"dumi-docs/guide":{"path":"guide","id":"dumi-docs/guide","parentId":"DocLayout"},"dumi-docs/index":{"path":"","id":"dumi-docs/index","parentId":"DocLayout"},"/packages/component-with-fixed/src/Page1/index":{"path":"page1","id":"/packages/component-with-fixed/src/Page1/index","parentId":"DocLayout"},"/packages/loading-with-cache/src/loading":{"path":"loading","id":"/packages/loading-with-cache/src/loading","parentId":"DocLayout"},"components/Page1/index":{"id":"components/Page1/index","path":"components/page1","parentId":"DocLayout","meta":{"_atom_route":true}},"component1s/loading":{"id":"component1s/loading","path":"component1s/loading","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/huabuyu/Documents/pnpm-monorepo/node_modules/.pnpm/dumi@2.4.13_@babel+core@7.26.0_@types+node@22.9.0_eslint@8.57.1_prettier@3.3.3_react-dom@18.3_uxlodu3ueg225w2obupv5nd4jy/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/huabuyu/Documents/pnpm-monorepo/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/huabuyu/Documents/pnpm-monorepo/node_modules/.pnpm/dumi@2.4.13_@babel+core@7.26.0_@types+node@22.9.0_eslint@8.57.1_prettier@3.3.3_react-dom@18.3_uxlodu3ueg225w2obupv5nd4jy/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'dumi-docs/guide': React.lazy(() => import(/* webpackChunkName: "dumi-docs__guide.md" */'/Users/huabuyu/Documents/pnpm-monorepo/dumi-docs/guide.md')),
'dumi-docs/index': React.lazy(() => import(/* webpackChunkName: "dumi-docs__index.md" */'/Users/huabuyu/Documents/pnpm-monorepo/dumi-docs/index.md')),
'/packages/component-with-fixed/src/Page1/index': React.lazy(() => import(/* webpackChunkName: "packages__component-with-fixed__src__Page1__index.md" */'/Users/huabuyu/Documents/pnpm-monorepo/packages/component-with-fixed/src/Page1/index.md')),
'/packages/loading-with-cache/src/loading': React.lazy(() => import(/* webpackChunkName: "packages__loading-with-cache__src__loading.md" */'/Users/huabuyu/Documents/pnpm-monorepo/packages/loading-with-cache/src/loading.md')),
'components/Page1/index': React.lazy(() => import(/* webpackChunkName: "packages__component-with-fixed__src__Page1__index.md" */'/Users/huabuyu/Documents/pnpm-monorepo/packages/component-with-fixed/src/Page1/index.md')),
'component1s/loading': React.lazy(() => import(/* webpackChunkName: "packages__loading-with-cache__src__loading.md" */'/Users/huabuyu/Documents/pnpm-monorepo/packages/loading-with-cache/src/loading.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/huabuyu/Documents/pnpm-monorepo/node_modules/.pnpm/dumi@2.4.13_@babel+core@7.26.0_@types+node@22.9.0_eslint@8.57.1_prettier@3.3.3_react-dom@18.3_uxlodu3ueg225w2obupv5nd4jy/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
